In [179]:
import pandas as pd
import numpy as np

In [180]:
def playdata_simplify(x):
    playdata = pd.read_excel(x)
    playdata['lead1'] = playdata['X1'].shift(-1)
    playdata['lead2'] = playdata['X1'].shift(-2)
    for i in range(len(playdata)):
        if pd.isna(playdata['X1'][i]):
            playdata['X1'][i] = playdata['lead1'][i]  
    for i in range(len(playdata)):
        if pd.isna(playdata['X1'][i]):
            playdata['X1'][i] = playdata['lead2'][i]  
    for i in range(len(playdata)):
        if pd.isna(playdata['X2'][i]):
            playdata['X2'][i] = playdata['X4'][i]
    playdata['Control'] = np.nan
    teama = playdata['X2'][8]
    teamb = playdata['X4'][8]
    for i in range(len(playdata)):
        if pd.isna(playdata['X4'][i]):
            playdata['Control'][i] = teama
        else:
            playdata['Control'][i] = teamb
    return playdata[['X1','X2','Control']]

In [181]:
playdata_simplify('PlayByPlay1.xlsx')

/var/folders/sl/yv5rc15959s3tcq5tgc529jc0000gn/T/ipykernel_83314/4171389871.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playdata['Control'][i] = teamb

,X1,X2,Control
0,Gardner-Webb (0-1),1st Period,Duke
1,Gardner-Webb (0-1),0,Duke
2,Duke (1-0),10,Duke
3,Game Date:,02/11/2022,Gardner-Webb
4,Location:,"Durham, N.C.",Gardner-Webb
...,...,...,...
222,02:49,Foul on DU Missy Biscardi.,Duke
223,02:49,"GOAL by GWU SHERROD,Brittany (FPGOAL) {free po...",Gardner-Webb
224,00:39,Draw control by DU Virginia Oursler.,Duke
225,00:39,"GOAL by DU Olivia Navaroli, Assist by Mattie S...",Duke
226,End of 4th Period,End of 4th Period,Duke